### ISSUE TITLE
Installing shunyaface on raspbian buster

### ISSUE THREAD

**Issue by rsingh2083** [shunyaos/shunyaface#7]
Hi colleague,

I tried instaling shunyaface on rp-buster, but it didnt work due to library issues. 
(There also was an error which complained about missing opencvconfig file.)
is there a work around to get it working on raspbian buster ?

**Comment by shunyaos** [comment]
No Currently this is not supported .Shunya face has many dependencies on the base OS for it to perform .
 so it cannot be ported to other os and expected to perform same hence this is not in development plan right now

**Comment by rsingh2083** [comment]
No problems. Just that HD monitor isnt working on shunyaOS-Raspberry-4. Hence asking if it could be ported to raspbian-rpi4 as that is supporting the HD monitor right now.

**Comment by shunyaos** [comment]
Noted !! we will update kernel on Shunya OS and upload new image in a week or so .
